backend:
  name: git-gateway
  branch: develop
  publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

i18n:
  structure: multiple_folders
  locales: [it, en]
  default_locale: it

collections:
  - name: "settings"
    label: "Impostazioni Sito"
    delete: false
    i18n: false
    files:
      - name: "website"
        label: "Website Settings"
        file: "src/content/settings/website.json"
        i18n: true
        fields:
          - { label: "Email di contatto", name: "contact_email", widget: "string", i18n: true }
          - { label: "Link GitHub", name: "github_url", widget: "string", i18n: false }
          - { label: "Link LinkedIn", name: "linkedin_url", widget: "string", i18n: false }

  - name: "pages"
    label: "Pagine"
    folder: "src/content/pages"
    create: true
    i18n: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo Pagina", name: "title", widget: "string", i18n: true }
      
      - { label: "Descrizione Colonna SX (Markdown)", name: "description_sx", widget: "markdown", i18n: true, required: false }
      - { label: "Descrizione Colonna DX (Markdown)", name: "description_dx", widget: "markdown", i18n: true, required: false }

      - { label: "Titolo Colonna SX", name: "sx_title", widget: "string", i18n: true, required: false }
      - { label: "Titolo Colonna DX", name: "dx_title", widget: "string", i18n: true, required: false }
      - { label: "Titolo Sezione Esperienze", name: "works_title", widget: "string", i18n: true, required: false }
      - { label: "Titolo Sezione Progetti", name: "projects_title", widget: "string", i18n: true, required: false }
      - { label: "Titolo Sezione Formazione", name: "education_title", widget: "string", i18n: true, required: false }

      - label: "Esperienze Lavorative"
        name: "works"
        widget: "relation"
        collection: "work_experiences"
        search_fields: ["title", "company"]
        value_field: "{{locale}}/{{slug}}"
        display_fields: ["title", "company"]
        multiple: true
        required: false
        i18n: true

      - label: "Progetti"
        name: "projects"
        widget: "relation"
        collection: "projects"
        search_fields: ["title"]
        value_field: "{{locale}}/{{slug}}"
        display_fields: ["title"]
        multiple: true
        required: false
        i18n: true

      - label: "Formazione"
        name: "education"
        widget: "relation"
        collection: "education"
        search_fields: ["title", "school"]
        value_field: "{{locale}}/{{slug}}"
        display_fields: ["title", "school"]
        multiple: true
        required: false
        i18n: true

  - name: "work_experiences"
    label: "Esperienze Lavorative"
    folder: "src/content/works"
    create: true
    i18n: true
    fields:
      - { label: "Ruolo", name: "title", widget: "string", i18n: true }
      - { label: "Azienda", name: "company", widget: "string", i18n: true }
      - { label: "Periodo", name: "period", widget: "string", i18n: true }
      - { label: "Descrizione (Markdown)", name: "description", widget: "markdown", i18n: true }

  - name: "education"
    label: "Formazione"
    folder: "src/content/education"
    create: true
    i18n: true
    fields:
      - { label: "Formazione", name: "title", widget: "string", i18n: true }
      - { label: "Istituto", name: "school", widget: "string", i18n: true }
      - { label: "Periodo", name: "period", widget: "string", i18n: true }
      - { label: "Descrizione (Markdown)", name: "description", widget: "markdown", i18n: true }

  - name: "projects"
    label: "Progetti"
    folder: "src/content/projects"
    create: true
    i18n: true
    fields:
      - { label: "Nome Progetto", name: "title", widget: "string", i18n: true }
      - { label: "Status/Tag", name: "status", widget: "string", i18n: true }
      
      - label: "Links Progetto"
        name: "links"
        widget: "list"
        i18n: true
        fields:
          - { label: "Testo del link", name: "label", widget: "string", i18n: true }
          - { label: "URL", name: "url", widget: "string", i18n: false }
          
      - { label: "Descrizione (Markdown)", name: "description", widget: "markdown", i18n: true }